development:
  adapter: postgresql
  encoding: unicode
  database: screen_time
  pool: 5
  username: coding
  password:
  timeout: 5000

  test:
  adapter: postgresql
  encoding: unicode
  database: screen_time
  pool: 5
  username: coding
  password:
  timeout: 5000
